# [[ Hunger is Stamina - v${project.version} ]]
#   Motivated by ASangarin, Created by X_Niter

# DO NOT TOUCH
config-version: 3

# NOTE: Any changes made here requires restart, reloading is not a feature in this addon!

# Is this Plugin Enabled [True = YES, False = NO]
IsPluginEnabled: true


####################################################################
#                     SPRINTING STAMINA                            #
####################################################################

# Do you want sprinting to drain stamina? [True = YES, False = NO]
StaminaCostForSprintingEnabled: True

# Stamina cost while sprinting, cost will apply every second the player is running
StaminaCostForSprinting: 1



####################################################################
#                     JUMPING STAMINA                              #
####################################################################

# Do you want jumping to drain stamina? [True = YES, False = NO]
StaminaCostForJumpingEnabled: True

# Stamina Cost for when a Player jumps
StaminaCostForJumping: 2


####################################################################
#                     SWIMMING STAMINA                             #
####################################################################

# Do you want swimming to drain stamina? [True = YES, False = NO]
StaminaCostForSwimmingEnabled: True

# Stamina cost while swimming, cost will apply every second the player is swimming
StaminaCostForSwimming: 3